version: '2'
services:
  telegram-updater-bot:
    image: 'aayushdutt/telegram-updator-bot'
    environment:
      - TELEGRAM_BOT_TOKEN=
    volumes:
      - 'telegramDatabase:databases'

volumes:
  telegram-updater-bot:
    driver: local